# Generated by Django 5.2.1 on 2025-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
