# Generated by Django 5.2.1 on 2025-06-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_expert_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='picture',
        ),
        migrations.AddField(
            model_name='expert',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to='User.userprofile'),
        ),
    ]
