# Generated by Django 5.2.1 on 2025-06-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_expert_picture_expert_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='profile',
        ),
    ]
