# Generated by Django 5.2.1 on 2025-06-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_expert_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
