# Generated by Django 5.2.17 on 2026-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_roles_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
