# Generated by Django 5.2.1 on 2026-09-25 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_roles_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Dado de baja'),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_username', models.CharField(max_length=150, verbose_name='Nombre de usuario afectado')),
                ('action', models.CharField(choices=[('CREATE', 'Creación de usuario'), ('UPDATE', 'Edición de usuario'), ('SOFT_DELETE', 'Baja lógica (Soft Delete)'), ('RESTORE', 'Reactivación de cuenta'), ('TOGGLE_ACTIVE', 'Cambio de estado activo/inactivo'), ('ROLE_CHANGE', 'Cambio de rol'), ('EXPERT_CHANGE', 'Asignación de especialidad'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('LOGIN', 'Inicio de sesión')], max_length=30, verbose_name='Acción')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles técnicos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario afectado')),
            ],
            options={
                'verbose_name': 'Registro de auditoría de usuario',
                'verbose_name_plural': 'Registros de auditoría de usuarios',
                'ordering': ['-timestamp'],
            },
        ),
    ]
