# Generated by Django 5.2.1 on 2025-06-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0001_initial'),
        ('User', '0002_expert_picture_alter_expert_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertword',
            name='expert',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.expert'),
            preserve_default=False,
        ),
    ]
