# Generated by Django 5.2.1 on 2025-06-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0002_expertword_expert'),
        ('User', '0002_expert_picture_alter_expert_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertword',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='User.expert'),
        ),
    ]
