# Generated by Django 5.2.1 on 2025-06-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0003_alter_expertword_expert'),
        ('User', '0007_alter_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expertword',
            name='word',
        ),
        migrations.AddField(
            model_name='expertword',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expertword',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_lists', to='User.expert'),
        ),
        migrations.AddField(
            model_name='expertword',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='lists', to='Counter.word'),
        ),
    ]
