# Generated by Django 5.2.1 on 2025-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0005_alter_expertword_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertword',
            name='words',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='expertword',
            name='words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
