# Generated by Django 5.2.1 on 2025-06-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0006_remove_expertword_words_delete_word_expertword_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalGlobalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
