# Generated by Django 5.2.1 on 2025-06-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0009_totalcount_company_totalcount_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='totalcount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='totalcount',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='totalcount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='totalcount',
            name='year',
        ),
    ]
