# Generated by Django 5.2.1 on 2026-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0010_alter_totalcount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='avg_sentence_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='avg_word_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='technical_words_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_sentences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='unique_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
