# Generated by Django 5.2.1 on 2026-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0011_report_avg_sentence_length_report_avg_word_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='inflesz_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
