# Generated by Django 5.2.1 on 2026-06-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0012_report_inflesz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConcealmentExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('excluded_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counter.report')),
            ],
        ),
    ]
