# Generated by Django 5.2.1 on 2026-06-12 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0013_report_extracted_text_concealmentexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcealmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('total_found', models.IntegerField()),
                ('total_valid', models.IntegerField()),
                ('total_discarded', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counter.report')),
            ],
        ),
        migrations.DeleteModel(
            name='ConcealmentExclusion',
        ),
    ]
