# Generated by Django 5.2.1 on 2026-06-12 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0014_concealmentreview_delete_concealmentexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcealmentParagraphReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_text', models.TextField()),
                ('occurrences', models.IntegerField()),
                ('discarded', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counter.concealmentreview')),
            ],
        ),
    ]
