# Generated by Django 5.2.1 on 2026-06-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0015_concealmentparagraphreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_syllables',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
