# Generated by Django 5.2.17 on 2026-09-23 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0016_report_total_syllables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concealmentreview',
            options={'ordering': ['-reviewed_at']},
        ),
        migrations.AddField(
            model_name='concealmentreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concealment_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
