# Generated by Django 5.2.17 on 2026-09-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0017_alter_concealmentreview_options_and_more'),
        ('Counter', '0017_concealmentreview_user'),
    ]

    operations = [
    ]
