# Generated by Django 5.2.1 on 2026-10-01 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0017_concealmentreview_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Counter.company'),
        ),
        migrations.AlterField(
            model_name='totalcount',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('project_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de temática')),
                ('color', models.CharField(default='blue', max_length=30, verbose_name='Color identificador')),
                ('icon', models.CharField(default='folder', max_length=50, verbose_name='Icono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Espacio de trabajo',
                'verbose_name_plural': 'Espacios de trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='Counter.workspace'),
        ),
        migrations.AddField(
            model_name='expertword',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_words', to='Counter.workspace'),
        ),
        migrations.AddField(
            model_name='report',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Counter.workspace'),
        ),
        migrations.AddField(
            model_name='totalcount',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_counts', to='Counter.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('workspace', 'ruc')},
        ),
        migrations.AlterUniqueTogether(
            name='totalcount',
            unique_together={('workspace', 'word')},
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor / Auditor'), ('viewer', 'Lector')], default='admin', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Counter.workspace')),
            ],
            options={
                'verbose_name': 'Membresía de espacio',
                'verbose_name_plural': 'Membresías de espacios',
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
