# Generated by Django 5.2.17 on 2026-09-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0018_merge_20260925_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concealmentreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='concealmentreview',
            name='reviewed_by',
        ),
    ]
