# Generated by Django 5.2.1 on 2026-10-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0019_migrate_to_default_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Counter.company'),
        ),
    ]
