# Generated by Django 5.2.1 on 2026-10-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0020_alter_report_company'),
        ('User', '0009_userprofile_deleted_at_userprofile_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertword',
            options={'verbose_name': 'Lista de palabras de experto', 'verbose_name_plural': 'Listas de palabras de expertos'},
        ),
        migrations.AlterField(
            model_name='company',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='Counter.workspace'),
        ),
        migrations.AlterField(
            model_name='expertword',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_words', to='Counter.workspace'),
        ),
        migrations.AlterField(
            model_name='report',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='Counter.workspace'),
        ),
        migrations.AlterField(
            model_name='totalcount',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_counts', to='Counter.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='expertword',
            unique_together={('workspace', 'expert', 'name')},
        ),
    ]
